// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: proto/serial.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendStringRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendStringRequest) Reset() {
	*x = SendStringRequest{}
	mi := &file_proto_serial_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendStringRequest) ProtoMessage() {}

func (x *SendStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_serial_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendStringRequest.ProtoReflect.Descriptor instead.
func (*SendStringRequest) Descriptor() ([]byte, []int) {
	return file_proto_serial_proto_rawDescGZIP(), []int{0}
}

func (x *SendStringRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_serial_proto protoreflect.FileDescriptor

const file_proto_serial_proto_rawDesc = "" +
	"\n" +
	"\x12proto/serial.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"'\n" +
	"\x11SendStringRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2H\n" +
	"\x06Serial\x12>\n" +
	"\n" +
	"SendString\x12\x18.proto.SendStringRequest\x1a\x16.google.protobuf.EmptyB\x0eZ\fserdbg/protob\x06proto3"

var (
	file_proto_serial_proto_rawDescOnce sync.Once
	file_proto_serial_proto_rawDescData []byte
)

func file_proto_serial_proto_rawDescGZIP() []byte {
	file_proto_serial_proto_rawDescOnce.Do(func() {
		file_proto_serial_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_serial_proto_rawDesc), len(file_proto_serial_proto_rawDesc)))
	})
	return file_proto_serial_proto_rawDescData
}

var file_proto_serial_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_serial_proto_goTypes = []any{
	(*SendStringRequest)(nil), // 0: proto.SendStringRequest
	(*emptypb.Empty)(nil),     // 1: google.protobuf.Empty
}
var file_proto_serial_proto_depIdxs = []int32{
	0, // 0: proto.Serial.SendString:input_type -> proto.SendStringRequest
	1, // 1: proto.Serial.SendString:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_serial_proto_init() }
func file_proto_serial_proto_init() {
	if File_proto_serial_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_serial_proto_rawDesc), len(file_proto_serial_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_serial_proto_goTypes,
		DependencyIndexes: file_proto_serial_proto_depIdxs,
		MessageInfos:      file_proto_serial_proto_msgTypes,
	}.Build()
	File_proto_serial_proto = out.File
	file_proto_serial_proto_goTypes = nil
	file_proto_serial_proto_depIdxs = nil
}
