// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: proto/serial.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaudRate      int64                  `protobuf:"varint,1,opt,name=baudRate,proto3" json:"baudRate,omitempty"`
	DataBits      int64                  `protobuf:"varint,2,opt,name=dataBits,proto3" json:"dataBits,omitempty"`
	Parity        int64                  `protobuf:"varint,3,opt,name=parity,proto3" json:"parity,omitempty"`
	StopBits      int64                  `protobuf:"varint,4,opt,name=stopBits,proto3" json:"stopBits,omitempty"`
	Rts           bool                   `protobuf:"varint,5,opt,name=rts,proto3" json:"rts,omitempty"`
	Dtr           bool                   `protobuf:"varint,6,opt,name=dtr,proto3" json:"dtr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mode) Reset() {
	*x = Mode{}
	mi := &file_proto_serial_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mode) ProtoMessage() {}

func (x *Mode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_serial_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mode.ProtoReflect.Descriptor instead.
func (*Mode) Descriptor() ([]byte, []int) {
	return file_proto_serial_proto_rawDescGZIP(), []int{0}
}

func (x *Mode) GetBaudRate() int64 {
	if x != nil {
		return x.BaudRate
	}
	return 0
}

func (x *Mode) GetDataBits() int64 {
	if x != nil {
		return x.DataBits
	}
	return 0
}

func (x *Mode) GetParity() int64 {
	if x != nil {
		return x.Parity
	}
	return 0
}

func (x *Mode) GetStopBits() int64 {
	if x != nil {
		return x.StopBits
	}
	return 0
}

func (x *Mode) GetRts() bool {
	if x != nil {
		return x.Rts
	}
	return false
}

func (x *Mode) GetDtr() bool {
	if x != nil {
		return x.Dtr
	}
	return false
}

type Port struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          string                 `protobuf:"bytes,1,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Port) Reset() {
	*x = Port{}
	mi := &file_proto_serial_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Port) ProtoMessage() {}

func (x *Port) ProtoReflect() protoreflect.Message {
	mi := &file_proto_serial_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Port.ProtoReflect.Descriptor instead.
func (*Port) Descriptor() ([]byte, []int) {
	return file_proto_serial_proto_rawDescGZIP(), []int{1}
}

func (x *Port) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type SendStringRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendStringRequest) Reset() {
	*x = SendStringRequest{}
	mi := &file_proto_serial_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendStringRequest) ProtoMessage() {}

func (x *SendStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_serial_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendStringRequest.ProtoReflect.Descriptor instead.
func (*SendStringRequest) Descriptor() ([]byte, []int) {
	return file_proto_serial_proto_rawDescGZIP(), []int{2}
}

func (x *SendStringRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Failed        bool                   `protobuf:"varint,1,opt,name=failed,proto3" json:"failed,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_serial_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_serial_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_serial_proto_rawDescGZIP(), []int{3}
}

func (x *Error) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

func (x *Error) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_proto_serial_proto protoreflect.FileDescriptor

const file_proto_serial_proto_rawDesc = "" +
	"\n" +
	"\x12proto/serial.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"\x96\x01\n" +
	"\x04Mode\x12\x1a\n" +
	"\bbaudRate\x18\x01 \x01(\x03R\bbaudRate\x12\x1a\n" +
	"\bdataBits\x18\x02 \x01(\x03R\bdataBits\x12\x16\n" +
	"\x06parity\x18\x03 \x01(\x03R\x06parity\x12\x1a\n" +
	"\bstopBits\x18\x04 \x01(\x03R\bstopBits\x12\x10\n" +
	"\x03rts\x18\x05 \x01(\bR\x03rts\x12\x10\n" +
	"\x03dtr\x18\x06 \x01(\bR\x03dtr\"\x1a\n" +
	"\x04Port\x12\x12\n" +
	"\x04port\x18\x01 \x01(\tR\x04port\"'\n" +
	"\x11SendStringRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"5\n" +
	"\x05Error\x12\x16\n" +
	"\x06failed\x18\x01 \x01(\bR\x06failed\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value2\xf4\x01\n" +
	"\x06Serial\x12.\n" +
	"\aGetMode\x12\x16.google.protobuf.Empty\x1a\v.proto.Mode\x12.\n" +
	"\aSetMode\x12\v.proto.Mode\x1a\x16.google.protobuf.Empty\x12.\n" +
	"\aGetPort\x12\x16.google.protobuf.Empty\x1a\v.proto.Port\x12$\n" +
	"\aSetPort\x12\v.proto.Port\x1a\f.proto.Error\x124\n" +
	"\n" +
	"SendString\x12\x18.proto.SendStringRequest\x1a\f.proto.ErrorB\x0eZ\fserdbg/protob\x06proto3"

var (
	file_proto_serial_proto_rawDescOnce sync.Once
	file_proto_serial_proto_rawDescData []byte
)

func file_proto_serial_proto_rawDescGZIP() []byte {
	file_proto_serial_proto_rawDescOnce.Do(func() {
		file_proto_serial_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_serial_proto_rawDesc), len(file_proto_serial_proto_rawDesc)))
	})
	return file_proto_serial_proto_rawDescData
}

var file_proto_serial_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_serial_proto_goTypes = []any{
	(*Mode)(nil),              // 0: proto.Mode
	(*Port)(nil),              // 1: proto.Port
	(*SendStringRequest)(nil), // 2: proto.SendStringRequest
	(*Error)(nil),             // 3: proto.Error
	(*emptypb.Empty)(nil),     // 4: google.protobuf.Empty
}
var file_proto_serial_proto_depIdxs = []int32{
	4, // 0: proto.Serial.GetMode:input_type -> google.protobuf.Empty
	0, // 1: proto.Serial.SetMode:input_type -> proto.Mode
	4, // 2: proto.Serial.GetPort:input_type -> google.protobuf.Empty
	1, // 3: proto.Serial.SetPort:input_type -> proto.Port
	2, // 4: proto.Serial.SendString:input_type -> proto.SendStringRequest
	0, // 5: proto.Serial.GetMode:output_type -> proto.Mode
	4, // 6: proto.Serial.SetMode:output_type -> google.protobuf.Empty
	1, // 7: proto.Serial.GetPort:output_type -> proto.Port
	3, // 8: proto.Serial.SetPort:output_type -> proto.Error
	3, // 9: proto.Serial.SendString:output_type -> proto.Error
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_serial_proto_init() }
func file_proto_serial_proto_init() {
	if File_proto_serial_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_serial_proto_rawDesc), len(file_proto_serial_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_serial_proto_goTypes,
		DependencyIndexes: file_proto_serial_proto_depIdxs,
		MessageInfos:      file_proto_serial_proto_msgTypes,
	}.Build()
	File_proto_serial_proto = out.File
	file_proto_serial_proto_goTypes = nil
	file_proto_serial_proto_depIdxs = nil
}
